### ISSUE TITLE
NPE at JsonEncoderDecoderClassCreator.java:346

### ISSUE THREAD

**Issue by cowwoc** [resty-gwt/resty-gwt#31]
Version: RestyGWT 1.0

I get the following exception while compiling my GWT application:

   Invoking generator org.fusesource.restygwt.rebind.RestServiceGenerator
      [ERROR] Generator 'org.fusesource.restygwt.rebind.RestServiceGenerator' threw an exception while rebinding 'com.holdmyspot.common.web.add.client.ClinicsResource'
java.lang.NullPointerException
        at org.fusesource.restygwt.rebind.JsonEncoderDecoderClassCreator.getFields(JsonEncoderDecoderClassCreator.java:346)
        at org.fusesource.restygwt.rebind.JsonEncoderDecoderClassCreator.getFields(JsonEncoderDecoderClassCreator.java:354)
        at org.fusesource.restygwt.rebind.JsonEncoderDecoderClassCreator.getFields(JsonEncoderDecoderClassCreator.java:342)
        at org.fusesource.restygwt.rebind.JsonEncoderDecoderClassCreator.generate(JsonEncoderDecoderClassCreator.java:128)
        at org.fusesource.restygwt.rebind.BaseSourceCreator.create(BaseSourceCreator.java:172)
        at org.fusesource.restygwt.rebind.JsonEncoderDecoderInstanceLocator.getEncoderDecoder(JsonEncoderDecoderInstanceLocator.java:114)
        at org.fusesource.restygwt.rebind.JsonEncoderDecoderInstanceLocator.encodeDecodeExpression(JsonEncoderDecoderInstanceLocator.java:141)
        at org.fusesource.restygwt.rebind.JsonEncoderDecoderInstanceLocator.decodeExpression(JsonEncoderDecoderInstanceLocator.java:126)
        at org.fusesource.restygwt.rebind.RestServiceClassCreator.writeMethodImpl(RestServiceClassCreator.java:329)
        at org.fusesource.restygwt.rebind.RestServiceClassCreator.generate(RestServiceClassCreator.java:182)
        at org.fusesource.restygwt.rebind.BaseSourceCreator.create(BaseSourceCreator.java:172)
        at org.fusesource.restygwt.rebind.RestServiceGenerator.generate(RestServiceGenerator.java:38)
        at com.google.gwt.dev.javac.StandardGeneratorContext.runGenerator(StandardGeneratorContext.java:427)
[...]

It's not clear what is wrong with my code.

**Comment by Armageddon-** [comment]
Was fixes with #93
