### ISSUE TITLE
Compilation failed if method has @Nonnull annotations

### ISSUE THREAD

**Issue by foal** [resty-gwt/resty-gwt#334]
If service interface (extends DirectRestService) contains @Nonnull (findBug version) annotated parameter the compilation failed with following exception:

```
[ERROR] Generator 'org.fusesource.restygwt.rebind.DirectRestServiceGenerator' threw an exception while rebinding 'com.jresearchsoft.booking.ft.admin.gwt.client.service.rest.ReservationUnitAdminRestService'
java.lang.IllegalArgumentException: Unsupported value for encodeAnnotationValue: ALWAYS
	at org.fusesource.restygwt.rebind.util.AnnotationCopyUtil.encodeAnnotationValue(AnnotationCopyUtil.java:113)
	at org.fusesource.restygwt.rebind.util.AnnotationCopyUtil.encodeAnnotationAttributes(AnnotationCopyUtil.java:57)
	at org.fusesource.restygwt.rebind.util.AnnotationCopyUtil.getAnnotationAsString(AnnotationCopyUtil.java:35)
	at org.fusesource.restygwt.rebind.DirectRestServiceInterfaceClassCreator.getAnnotationsAsStringArray(DirectRestServiceInterfaceClassCreator.java:111)
	at org.fusesource.restygwt.rebind.DirectRestServiceInterfaceClassCreator.getAnnotationsAsString(DirectRestServiceInterfaceClassCreator.java:99)
	at org.fusesource.restygwt.rebind.DirectRestServiceInterfaceClassCreator.getMethodParameters(DirectRestServiceInterfaceClassCreator.java:71)
	at org.fusesource.restygwt.rebind.DirectRestServiceInterfaceClassCreator.generate(DirectRestServiceInterfaceClassCreator.java:63)
	at org.fusesource.restygwt.rebind.BaseSourceCreator.create(BaseSourceCreator.java:280)
	at org.fusesource.restygwt.rebind.DirectRestServiceGenerator.generate(DirectRestServiceGenerator.java:17)
	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
	at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:519)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:487)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.maybeHandleMagicMethodCall(UnifyAst.java:415)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:402)
	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
	at com.google.gwt.dev.jjs.ast.JDeclarationStatement.traverse(JDeclarationStatement.java:49)
	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:778)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1401)
	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:896)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:362)
	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:175)
	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:134)
	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:135)
	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:113)
	at com.google.gwt.dev.codeserver.JobRunner.access$000(JobRunner.java:37)
	at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by foal** [comment]
Not a big issue, but the error is very unclear.

**Comment by brazeneric** [comment]
I think this is actually a bigger issue, as it has to do with passing an enum as an annotation argument (in this case, "When.ALWAYS"), which isn't exclusive to @Nonnull.
